print("Hello Word!")
print("Hello Again")
print("I like typing this.")
print("This is fun")
print('Yay! Printing.')
print("I'd much rater you 'not'.")
print('I "said" do not touch this.')
print('This line is done with one colon')
print("This line is done with two colons")
